export const records = [
    {
        productId: '1187758',
        ean: null,
        artist: 'Ray Charles',
        album: 'Come Live With Me',
        labels: 'Tangerine Records',
        releaseDate: '2025-08-22',
        url: 'https://www.muziker.cz/ray-charles-come-live-with-me-lp',
        price: 769,
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
    {
        productId: '1263728',
        ean: null,
        artist: 'Ray Charles',
        album: 'Modern Sounds In Country And Western Music (Reissue) (180 g)',
        labels: 'Waxtime',
        releaseDate: null,
        url: 'https://www.muziker.cz/ray-charles-modern-sounds-in-country-and-western-music-reissue-180-g-lp',
        price: 411,
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
    {
        productId: '338494',
        ean: null,
        artist: 'Michael Jackson',
        album: 'Thriller',
        labels: 'Epic, MJJ Productions, Sony Music',
        releaseDate: '2016-04-15',
        url: 'https://www.muziker.cz/michael-jackson-thriller-gatefold-sleeve-vinyl-lp',
        price: 597,
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
    {
        productId: '350894',
        ean: null,
        artist: 'Kraftwerk',
        album: 'Autobahn (Blue Coloured)',
        labels: 'Vertigo',
        releaseDate: '2020-12-31',
        url: 'https://www.muziker.cz/kraftwerk-autobahn-blue-coloured-lp',
        price: 1020,
        currency: 'CZK',
        stock: 'preorder',
        store: 'Muziker',
    },
    {
        productId: '350896',
        ean: null,
        artist: 'Kraftwerk',
        album: 'Die Mensch-Maschine (Red Coloured)',
        labels: 'Parlophone',
        releaseDate: '2020-12-31',
        url: 'https://www.muziker.cz/kraftwerk-die-mensch-maschine-red-coloured-lp',
        price: 600,
        currency: 'CZK',
        stock: 'preorder',
        store: 'Muziker',
    },
    {
        productId: '350897',
        ean: null,
        artist: 'Kraftwerk',
        album: 'Radio-Activity',
        labels: 'Capitol Records',
        releaseDate: '2020-12-31',
        url: 'https://www.muziker.cz/kraftwerk-radio-activity-vinyl-lp',
        price: 1450,
        currency: 'CZK',
        stock: 'out_of_stock',
        store: 'Muziker',
    },
];
