export const records = [
    {
        productId: '1187758',
        ean: null,
        artist: 'Ray Charles',
        album: 'Come Live With Me',
        labels: 'Tangerine Records',
        releaseDate: '2025-08-22',
        url: 'https://www.muziker.cz/ray-charles-come-live-with-me-lp',
        price: 769,
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
    {
        productId: '1263728',
        ean: null,
        artist: 'Ray Charles',
        album: 'Modern Sounds In Country And Western Music (Reissue) (180 g)',
        labels: 'Waxtime',
        releaseDate: '2013-02-15',
        url: 'https://www.muziker.cz/ray-charles-modern-sounds-in-country-and-western-music-reissue-180-g-lp',
        price: 411,
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
    {
        productId: '338494',
        ean: null,
        artist: 'Michael Jackson',
        album: 'Thriller',
        labels: 'Epic, MJJ Productions, Sony Music',
        releaseDate: '2016-04-15',
        url: 'https://www.muziker.cz/michael-jackson-thriller-gatefold-sleeve-vinyl-lp',
        price: 675,
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
    {
        productId: '350896',
        ean: null,
        artist: 'Kraftwerk',
        album: 'Die Mensch-Maschine (Red Coloured)',
        labels: 'Parlophone',
        releaseDate: '2020-12-31',
        url: 'https://www.muziker.cz/kraftwerk-die-mensch-maschine-red-coloured-lp',
        price: 1029, // price
        currency: 'CZK',
        stock: 'preorder', // stock
        store: 'Muziker',
    },
    {
        productId: '350897',
        ean: null,
        artist: 'Kraftwerk',
        album: 'Radio-Activity',
        labels: 'Capitol Records',
        releaseDate: '2020-12-31',
        url: 'https://www.muziker.cz/kraftwerk-radio-activity-vinyl-lp',
        price: 839,
        currency: 'CZK',
        stock: 'out_stock', // stock
        store: 'Muziker',
    },
    {
        productId: '429771',
        ean: null,
        artist: 'Metallica',
        album: 'Metallica (2021) (2 LP)',
        labels: 'Universal Music',
        releaseDate: '2021-09-10',
        url: 'https://www.muziker.cz/metallica-metallica-2-lp-2021',
        price: 1700, //price
        currency: 'CZK',
        stock: 'in_stock',
        store: 'Muziker',
    },
];
